-- AlterTable
ALTER TABLE "Pokemon" ADD COLUMN     "base_experience" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "is_default" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "order" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "sprite" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "type1" TEXT NOT NULL DEFAULT '',
ADD COLUMN     "type2" TEXT DEFAULT '',
ADD COLUMN     "weight" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "id" DROP DEFAULT;
DROP SEQUENCE "pokemon_id_seq";
